# Argos Visual Testing Configuration
# Documentation: https://docs.argos-ci.com

# Project token is stored as GitHub secret ARGOS_TOKEN
# Token: argos_49188c6c4bf9042c7c877bf47aaa3cb484

# Base URL for visual testing
baseUrl: http://localhost:3000

# Screenshot directory (if using custom screenshot tooling)
# screenshots: ./argos-screenshots

# Ignore patterns for screenshots
ignore:
  - "**/node_modules/**"
  - "**/.next/**"
  - "**/coverage/**"
