# Codacy configuration file
# This file configures which tools and patterns Codacy should use

# Exclude files from analysis
exclude_paths:
  - ".next/**"
  - "node_modules/**"
  - "coverage/**"
  - "dist/**"
  - "build/**"
  - "out/**"
  - "public/sw.js"
  - "**/*.min.js"
  - "**/*.bundle.js"

# Language-specific settings
languages:
  TypeScript:
    extensions:
      - ".ts"
      - ".tsx"
  JavaScript:
    extensions:
      - ".js"
      - ".jsx"
      - ".mjs"
  CSS:
    extensions:
      - ".css"
      - ".scss"

# Engine configuration
# Note: ESLint patterns are controlled via the Codacy UI or coding standard
# This project uses modern ES2015+ features - disable ES5 compatibility checks
engines:
  eslint9:
    enabled: true
    # Use the project's eslint.config.mjs
  eslint:
    enabled: false
    # Disable the old ESLint with default Codacy patterns
  duplication:
    enabled: true
    exclude_paths:
      - "src/__tests__/**"
      - "**/*.test.ts"
      - "**/*.test.tsx"
  complexity:
    enabled: true
